name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and test stage for the "development" target
      - name: Build and test (Development)
        run: |
          docker build -t docker-nest-postgres:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-nest-postgres:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # Build and push stage for the "production" target
      - name: Build and push (Production)
        run: |
          docker build -t docker-nest-postgres:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-nest-postgres:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
